# relevant docs:
# - http://docs.travis-ci.com/user/languages/groovy/
# - http://blog.freeside.co/2013/02/26/grails-builds-on-travis-ci/

sudo: required

language: groovy

services: docker

jdk:
  - oraclejdk7

script: gradle check
