# relevant docs:
# - http://docs.travis-ci.com/user/languages/groovy/
# - http://blog.freeside.co/2013/02/26/grails-builds-on-travis-ci/

language: groovy

services:
  - docker

jdk:
  - oraclejdk7

script: gradle check

after_success:
  - if [ "$TRAVIS_BRANCH" == "docker" ]; then
    docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS;
    export REPO=gkiko/streama;
    export TAG=latest;
    docker build -f Dockerfile -t $REPO:$COMMIT .;
    docker tag $REPO:$COMMIT $REPO:$TAG;
    docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER;
    docker push $REPO;
    fi
