# relevant docs:
# - http://docs.travis-ci.com/user/languages/groovy/
# - http://blog.freeside.co/2013/02/26/grails-builds-on-travis-ci/

dist: precise

sudo: required

language: groovy

services: docker

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t gkiko/streama:travis-test .
  - docker images
  - docker push gkiko/streama:travis-test
